### PR TITLE
Updates codemirror to 4.10

### PR DESCRIPTION
**Pull request by justintaft**
Escape,backspace, etc. worked while in vim mode. Tried variety of vim commands and worked.
Python highlighting works, but python keywords do not show up in auto complete, unless typed first.
Edit: Per #1797

### CODE REVIEW

**Comment by cldwalker** [comment]
Since atom-shell is the current focus, I'm holding off on trying this until later in the week

**Comment by justintaft** [comment]
Without the loading of simple mode, the editor failed to load

```
Invalid behaviors file: /Users/justin/programming/LightTable/deploy. Behaviors must be either a vector or a map.
		Invalid behavior: :lt.objs.editor/init-codemirror
		TypeError: Object function CodeMirror(place, options) {
		    if (!(this instanceof CodeMirror)) return new CodeMirror(place, options);
		
		    this.options = options = options ? copyObj(options) : {};
		    // Determine effective options based on given values and defaults.
		    copyObj(defaults, options, false);
		    setGuttersForLineNumbers(options);
		
		    var doc = options.value;
		    if (typeof doc == "string") doc = new Doc(doc, options.mode);
		    this.doc = doc;
		
		    var display = this.display = new Display(place, doc);
		    display.wrapper.CodeMirror = this;
		    updateGutters(this);
		    themeChanged(this);
		    if (options.lineWrapping)
		      this.display.wrapper.className += " CodeMirror-wrap";
		    if (options.autofocus && !mobile) focusInput(this);
		    initScrollbars(this);
		
		    this.state = {
		      keyMaps: [],  // stores maps added by addKeyMap
		      overlays: [], // highlighting overlays, as added by addOverlay
		      modeGen: 0,   // bumped when mode/overlay changes, used to invalidate highlighting info
		      overwrite: false, focused: false,
		      suppressEdits: false, // used to disable editing during key handlers when in readOnly mode
		      pasteIncoming: false, cutIncoming: false, // help recognize paste/cut edits in readInput
		      draggingText: false,
		      highlight: new Delayed(), // stores highlight worker timeout
		      keySeq: null  // Unfinished key sequence
		    };
		
		    // Override magic textarea content restore that IE sometimes does
		    // on our hidden textarea on reload
		    if (ie && ie_version < 11) setTimeout(bind(resetInput, this, true), 20);
		
		    registerEventHandlers(this);
		    ensureGlobalHandlers();
		
		    startOperation(this);
		    this.curOp.forceUpdate = true;
		    attachDoc(this, doc);
		
		    if ((options.autofocus && !mobile) || activeElt() == display.input)
		      setTimeout(bind(onFocus, this), 20);
		    else
		      onBlur(this);
		
		    for (var opt in optionHandlers) if (optionHandlers.hasOwnProperty(opt))
		      optionHandlers[opt](this, options[opt], Init);
		    maybeUpdateLineNumberWidth(this);
		    for (var i = 0; i < initHooks.length; ++i) initHooks[i](this);
		    endOperation(this);
		  } has no method 'defineSimpleMode'
		    at eval (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/mode/dockerfile/dockerfile.js:22:14)
		    at eval (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/mode/dockerfile/dockerfile.js:10:5)
		    at eval (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/mode/dockerfile/dockerfile.js:11:3)
		    at eval (native)
		    at c (file:///Users/justin/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:21488:41)
		    at a (file:///Users/justin/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:21496:18)
		    at Function.lt.objs.editor.__BEH__init_codemirror (file:///Users/justin/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:24418:246)
		    at c (file:///Users/justin/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6196:14)
		    at a (file:///Users/justin/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6236:18)
		    at c (file:///Users/justin/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:20443:76)
		Invalid behavior: :lt.objs.opener/open-transient-editor
		TypeError: Object #<Object> has no method 'startState'
		    at Object.startState (/Users/justin/programming/LightTable/deploy/plugins/html/codemirror/htmlmixed.js:72:28)
		    at CodeMirror.startState (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:4801:35)
		    at getStateBefore (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:1576:25)
		    at getLineStyles (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:6073:62)
		    at buildLineContent (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:6133:40)
		    at updateExternalMeasurement (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:1652:30)
		    at prepareMeasureForLine (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:1686:14)
		    at measureChar (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:1661:36)
		    at endOperation_R2 (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:2158:26)
		    at endOperations (/Users/justin/programming/LightTable/deploy/core/node_modules/codemirror/lib/codemirror.js:2124:7)
```

**Comment by justintaft** [comment]
Ah, sorry did not see that chunk of code. The "mode" path has changed so none of the modes loaded.  Will  get rid of the explicit loading of mode/simple.js and update the modes path for the doseq fn.

**Comment by justintaft** [comment]
Pull is not ready. Ran into some errors while using vim mode.

These errors occurred while leaving exit mode.
Uncaught TypeError: Cannot read property 'height' of undefined
vim.js [4648]	exitInsertMode
codemirror.js [3270]	doHandleBinding
codemirror.js [3334]	anonymous
codemirror.js [5076]	CodeMirror.lookupKey
codemirror.js [3284]	lookupKeyForEditor
codemirror.js [3300]	dispatchKey
codemirror.js [3334]	handleKeyBinding
codemirror.js [3353]	onKeyDown
codemirror.js [2248]	anonymous



Uncaught TypeError: Cannot read property 'visualBlock' of null
vim.js [4648]	exitInsertMode
codemirror.js [3270]	doHandleBinding
codemirror.js [3334]	anonymous
codemirror.js [5076]	CodeMirror.lookupKey
codemirror.js [3284]	lookupKeyForEditor
codemirror.js [3300]	dispatchKey
codemirror.js [3334]	handleKeyBinding
codemirror.js [3353]	onKeyDown
codemirror.js [2248]	anonymous

**Comment by cldwalker** [comment]
I'm holding off on looking at this until atom-shell lands

**Comment by justintaft** [comment]
After I updated vim.js to use the new version with code mirror, things are working much better. I can't re produce any errors by leaving insertion mode.

Thanks to seancorfield for reminding me vim is a plugin and the key mapping isn't part of light table's base anymore.

**Comment by justintaft** [comment]
PHP  code hinting/highlighting is not working.

**Comment by BenjaminVanRyseghem** [comment]
Now version 5.4 is out.

Should we try to focus on this one after the 0.8.0 release?

**Comment by cldwalker** [comment]
Closing as this was WIP and is now out of date with newer versions in CM. Tracking in #1797 and hoping we can look at it for 0.8.1

**Pull request closed without merging**
