### PR TITLE
script which makes light table linux desktop icon

### PR DESCRIPTION
**Pull request by wilsonjm**
please see the file "make_user_icon.sh"

### CODE REVIEW

**Comment by NicolasPetton** [comment]
I run Fedora and I have an icon, should this one be closed?

**Comment by kenny-evitt** [comment]
@NicolasPetton You ran this script to create a desktop icon?

@wilsonjm Please squash your commits. I'll test this when I have a chance.

**Comment by wilsonjm** [comment]
I haven't committed since like March 2014

On Sunday, August 30, 2015, kenny-evitt <notifications@github.com> wrote:

> @NicolasPetton <https://github.com/NicolasPetton> You ran this script to
> create a desktop icon?
>
> @wilsonjm <https://github.com/wilsonjm> Please squash your commits. I'll
> test this when I have a chance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LightTable/LightTable/pull/1259#issuecomment-136174479>
> .
>


-- 
Jason Wilson
B.S. Computer Science
College of Charleston c/o 2014
cell: (843) 452-2790

**Comment by kenny-evitt** [comment]
@wilsonjm Comment if you're still interested in this and I'll re-open it.

**Comment by cldwalker** [comment]
@wilsonjm Thanks for your script. I've linked to it in [a wiki section for useful scripts](https://github.com/LightTable/LightTable/wiki#miscellaneous-scripts) so other users can find it
As explained in #1659 having this script in LightTable won't make since LightTable is agnostic to install locations and a Ubuntu desktop icon requires it

**Pull request closed without merging**
