### PR TITLE
Add SCons file types to load Python behavior

### PR DESCRIPTION
**Pull request by sawcordwell**

### CODE REVIEW

**Comment by sawcordwell** [comment]
Not sure if it would be best to add a new line or add the SCons filenames to the Python entry, I thought this seemed nicest. Also, not sure about the order with the captial letter.

**Comment by cldwalker** [comment]
Thanks for the pull but this should be done against the Python plugin
@ibdknox This is introducing a library-specific filetype for lang which we haven't done before. Do we want to start doing this?

**Comment by ibdknox** [comment]
I feel like the best thing to do is to have plugins for libraries. It seems
like a slippery slope trying to put library specific stuff into the
language plugins directly.

**Comment by cldwalker** [comment]
@sawcordwell Thanks for the PR but I agree with Chris that having language plugins track all possible library extensions could be a never-ending task. I recommend putting this behavior in your user.behaviors or if you'd like to share with others publish it as a plugin

**Comment by sawcordwell** [comment]
fair enough, I did put it in my user.behaviors file. Thanks for the info

**Pull request closed without merging**
