### PR TITLE
Start a package.json for vanilla node dependencies

### PR DESCRIPTION
**Pull request by cldwalker**
Continuing where #1772 started, I've been able to identify 4 node packages that are vendored and can thus be declared in a package.json. The rest are either forked or not used. I've updated doc/for-committers.md with more details.
@ibdknox I've noticed the following node dependencies are not used - ~~bencode, harbor, jshint~~, marked, source-map, walkdir, watchr, acorn.js . Actually on the atom-shell, I saw bencode [was modified](https://github.com/LightTable/LightTable/commit/d951744c5832e444d782f777f001d8377a07cab0) but it's not used, right? Any objections to removing these on this pull?

### CODE REVIEW

**Comment by kenny-evitt** [comment]
@cldwalker What should be done with this?

**Comment by cldwalker** [comment]
@kenny-evitt Thanks for the reminder. I'll look at this soon so it can go with 0.8.0

**Comment by cldwalker** [comment]
@kenny-evitt Ready for review. There should be no runtime code effected by this accept for a minor comment. But of course I QAed this on osx. For removed node packages, I verified their history with `git log -S` and a [LightTable org search](https://github.com/search?utf8=%E2%9C%93&q=proc%2Fexec+user%3ALightTable&type=Code&ref=searchresults) to make sure they weren't used. bencode, harbor and jshint are still used by other plugins and I'll make an issue for it

**Comment by kenny-evitt** [comment]
@cldwalker This looks good. Anything else to be done before merging?

**Comment by cldwalker** [comment]
Nope. Thanks for looking it over :)

**Pull request merged**
