### PR TITLE
WIP: Update electron version

### PR DESCRIPTION
**Pull request by prertik**
I have in this branch taken my work's base on @sbauer322's branch and updated the electron. The electron version 0.37.8 doesn't fix the issue of displaying random characters while opening files. I found electron v1.8.* to fix these problems and will be fixed and updated in future commits.

### CODE REVIEW

**Comment by prertik** [comment]
Additionally, I want to maintain this project.

**Comment by prertik** [comment]
Yes, electron has been updated to v0.37.8 and works. But sadly, electron
v0.37.8 doesn't fix the font issues, electron v1.8.* does (which I have
done in another branch) and certain other changes are required to properly
make this work.

I have made this PR, WIP because I have to fix the commit messages and need
to finalize this for a release.

**Comment by sbauer322** [comment]
Got it, thanks!

From what I remember, I think my goal at the time was to get to later versions of electron but there were some unknown breaking changes between v0.37.8 and later versions.

**Comment by prertik** [comment]
Hey, @sbauer322 little help is needed here! I've been trying different things for the past week and haven't been fully able to update.

**Comment by prertik** [comment]
If you build LightTable from my branch and run it, you will see the problem.

**Comment by prertik** [comment]
error

I was talking about this problem, @sbauer322! Steps to reproduce: Cherry-pick my commits and run `script/build.sh` then run `./builds/lighttable-0.9.0-linux/LightTable`. After that open a new file or open any `.clj` file and try evaluating any basic Clojure arithmetic.

**Comment by sbauer322** [comment]
Thank you for the screenshot - it makes it easier to try and assist. I've seen this error and it thoroughly stumped me back then as well. As far as I remember, something is in being eval'd in https://github.com/LightTable/LightTable/blob/master/deploy/core/node_modules/lighttable/background/threadworker.js that tries causes the error, but I am not sure what. 

I'd guess that it has to do with the `.apply` on line 43 but I am only just starting to investigate again after months of not looking at the code.

The https://github.com/LightTable/LightTable/blob/master/deploy/core/node_modules/lighttable/ directory is important and should not be gitignored.

**Comment by sbauer322** [comment]
That certainly is interesting - I never thought of trying that before. If you go back to the normal clojurescript version but remove all plugins and then build, does the same thing happen?

**Comment by sbauer322** [comment]
Sorry, I meant whatever version of clojurescript was being used prior to switching to `0.0-3211`. I'm curious if the Clojure plugin could be part of the problem or maybe something about cljsDep.js https://github.com/LightTable/LightTable/blob/master/src-cljsdeps/core.cljs. Just a couple ideas, but I can't say if they are worthwhile to investigate... perhaps there is a breaking change somewhere between the two cljs versions?

**Comment by prertik** [comment]
Nope. That's not it! Additionally, I found out that updating electron version makes the eval feature of LightTable unusable. I changed the Clojure and Clojurescript version on your branch `upgrade-to-electron-v2` which my pull request was based on. I tried evaluating the form using `ctrl+enter` or `ctrl+shift+enter`. It doesn't work!

**Comment by prertik** [comment]
So, I'm guessing your skepticism towards `cljsDeps.js` is correct. I think there are some breaking changes.

**Comment by prertik** [comment]
Okay, I fixed the `threaderror` issue. But, sadly the eval feature of LT still doesn't work. :(

**Comment by prertik** [comment]
@sbauer322, LT team & contributors,

Hmm, So, I diagnosed the error to the Clojure plugin. LT hasn't been updated properly for more than 3 years. During these times, interesting works were done to update LT but everyone reached a roadblock now and then. 3 years is a long time in ClojureScript ecosystem as during the time ClojureScript went through **a lot** of changes and even **electron** did.

LT was missing active maintainer and active contributor due to which the issues keep on piling on LT. The roadmap hasn't been addressed for years. Now, when I expressed my desire to maintain LT. I meant it strongly, as LT was a good editor and was way awesome than other editors when it was released but now, every other editor has left LT far behind. My goal is to bring LT to 2019 then, enhance it further adding features like remote editing, saving to the cloud, and lots of other interesting things which I'll update further. Furthermore, LT is missing lots of documents describing the weird choices the developers made during the early stage of LT development. LT smells more JS than CLJS. Maybe due to the early stage of CLJS and due to how amazing LT was being made. So, to bring it to current CLJS and make it more Clojure and less JS, lots of re-write is a **must**.

The reason for me to write all this is to inform the current maintainers that I want commit access and termed as Maintainer from here on forward. As there are lots of updates, I need to do the in repositories on LT. The cycle of waiting review and getting my pull request merged will slow my process and eventually make me frustrated. Had this been an active developed project, I wouldn't have asked to be Maintainer soon. I would have committed alot of changes first, and then asked for it but since, my changes need alot of updates in plugins, the main repo and all, I need access. For eg: In this pull request, I have fixed the `threaderror` issue but the eval feature isn't working as the Clojure plugin of LT needs to be updated too to make new version of LT work as it should. Otherwise we are left like notepad-like text editor without the eval feature.

If the current owners disagree with allowing me commit access and making me a Maintainer, I'll understand and follow the old Unix hackers' saying, "if you don't like something, fork it." and will work on a new editor forked from LightTable.

P.S.: The further development of LT like adding additional features need some funds and I think I'll apply to Clojurists Together for LT.

**Comment by Mouvedia** [comment]
I did a minimal background check on him—nothing too intrusive or official—and found https://summerofcode.withgoogle.com/archive/2018/projects/5389615745728512/

You were accepted as a GSOC student and contributed to git; that's enough for me.

**Comment by prertik** [comment]
Thanks, @Mouvedia, I did just now. If this doesn't work out, I have planned to create my own fork of LT in a new direction. I'll notify you further.

**Comment by prertik** [comment]
@Mouvedia 
So, according to Code Shelter team, I do not have enough credential for them considering me and additionally, they think that I will be directly added as Maintainer from here.

**Comment by prertik** [comment]
So, anyway, I created a place to keep a fork of LT for some time and then re-write everything from the ground up. I'll release a new pre-release version tomorrow. It can be found here: [Dublo](https://github.com/Dublo) [LightTable-forked](https://github.com/Dublo/LightTable-forked).

**Comment by myg133** [comment]
https://github.com/myg133/LightTable/tree/develop

**Comment by prertik** [comment]
Hmmm. @myg133, it seems you already, were way ahead. Sadly, your contributions couldn't be contributed to LT way earlier. Anyways, I have stored a new fork of LT and possible re-write of LT in [Dublo](https://github.com/Dublo). If you like to contribute there and help me there, I would gladly give you commit access.

**Pull request closed without merging**
