### PR TITLE
use pango v1.40.5-1 - Closes #2343

### LINKED ISSUE #2343: I cannot see the names of the files properly
Version 0.8.1 when I open a file I see this
captura de pantalla_2017-06-28_17-38-28

### PR DESCRIPTION
**Pull request by dukex**
This PR embedded the libpangoft2-1.0.so.0.4000.5 in project on linux release

### CODE REVIEW

**Comment by tdan** [comment]
Fix doesn't solve the issue for me. I have Fedora 27 box

**Comment by RCL-Loren** [comment]
This fix does not solve the problem for me using lubuntu 17.1 after building with this change.

**Comment by bakirillov** [comment]
This fix doesn't work for me. Ubuntu Budgie 17.10.

**Comment by sbauer322** [comment]
Based on comments in this PR, it does not solve the problem for multiple Linux distributions, so we will be declining the PR.

**Pull request closed without merging**
