### PR TITLE
External Browser: Try a default port for socket.io first

### PR DESCRIPTION
**Pull request by jakubholynet**
Try to use a hard-coded port, 5678, and only ask
for a random free port when it is not available.
Users that have only one connection thus get by
most of the time without having to change the port
in their HTML whenever LT restarts.

I think it is also better to log errors than to
swallow them.
I am, of course, open to discussions.

### CODE REVIEW

**Comment by tclev** [comment]
I'd like to bump this issue if possible. Unless there is another way that I don't know about, it's cumbersome to have always change my html every time I restart LightTable.

**Comment by cldwalker** [comment]
@kenny-evitt @rundis This looks reasonable to me. I'll QA tonight. I'll be merging tomorrow unless there's a concern

**Comment by cldwalker** [comment]
@jakubholynet Thanks for the PR! Better late than never

**Comment by jakubholynet** [comment]
<3

**Pull request merged**
