### PR TITLE
Improve new user experience

### PR DESCRIPTION
**Pull request by cldwalker**
Over the past couple weeks, I've had some designers (non backend people) at my coworking space trying out LightTable. The feedback was pretty consistent in that user.keymap and user.behaviors explanations were confusing (they don't know what diffs and objects are). To address this I revamped the user.keymap and user.behaviors explanations to be more practical and created a separate document for describing configuration in detail. I also added menu items for functionality users were looking for but not finding since they weren't familiar with the command pane. Even when they found the command pane, these new users preferred to access them through the menu. Given configuration/settings and the plugin manager are integral parts of using LightTable, I think adding them to the menu will help new users.

### CODE REVIEW

**Comment by cldwalker** [comment]
@rundis @kenny-evitt Will merge this end of day tomorrow unless there are any concerns

**Comment by rundis** [comment]
Looks good to me.

**Comment by cldwalker** [comment]
Thanks for looking it over!

**Comment by kenny-evitt** [comment]
Nice!

**Pull request merged**
