### PR TITLE
Add docstrings per #1715

### PR DESCRIPTION
**Pull request by cldwalker**
Finally got around to this. Had to do code reading for some of this. Hopefully this will make LT more accessible and encourage us to document more :)
@kenny-evitt @rundis  Feedback welcome on anything that's unclear

### CODE REVIEW

**Comment by kenny-evitt** [comment]
@cldwalker This is great! Feel free to merge unless you want @rundis to review it first.

**Comment by BenjaminVanRyseghem** [comment]
:clap: :clap: :beers: :smile:

**Comment by cldwalker** [comment]
Two eyes is plenty :)

**Comment by rundis** [comment]
:+1: 
Nice work !

**Pull request merged**
