### PR TITLE
Rebrand built exe for Windows

### PR DESCRIPTION
**Pull request by TimothyDJewell**
By default it has GitHub's information, as reported in #2030.  I know the contributing guidelines say "core team only" for scripts/, but this change is quite straightforward and not directly related to the actual build process.  For me, this has served as a distraction every time I go to use LightTable on my Windows machine (seeing Electron's icon and branding), so I'd like to just fix it.  I'm not that familiar with cygwin/this project's processes, so please don't hesitate to point out where I'm wrong.  I'll do my best to fix things up however I can.

I built the .ico file in GIMP from the existing lticon.png using the instructions described [on StackOverflow](http://stackoverflow.com/a/10819673).  The requirement of this PR should be simply that [rcedit.exe](https://github.com/electron/rcedit) be located somewhere on the build machine's path.  If it's not there, it should just fall back to the existing behavior, but with a console output from which and echo indicating the failure to rebrand.

Other relevant links:
 - [The electron team's notes about how to rebrand for Windows](http://electron.atom.io/docs/tutorial/application-distribution/#rebranding-with-downloaded-binaries)
 - [grunt-rcedit](https://github.com/unindented/grunt-rcedit#version-information) had the most helpful information about which version strings, though it points back to MSDN.

### CODE REVIEW

**Comment by sbauer322** [comment]
Thanks for this @TimothyDJewell, I will be able to give it a try later this week.

If anyone else wishes to review it then feel free to do so!

**Comment by sbauer322** [comment]
Gave this a try and it mostly works! Pretty nice to see the Light Table icon on Windows. Thank you @TimothyDJewell!

Just a couple things:

- Could you update `doc/developer-install`'s Window's section to specify that rcedit will be necessary. Also, please mention that there should be a release of rcedit available at https://github.com/electron/rcedit/releases ... Their README doesn't indicate that there is a release (as opposed to building it), which I imagine will be misleading to someone at some point.
- The Light Table icon is not displayed for certain views. They are 'small', 'list', and 'details'. Works for all the rest though (including as a shortcut on the desktop). Could you address this, please?

Overall, this looks great.

**Comment by TimothyDJewell** [comment]
Sure, I'll get on the documentation.  With the icon, I ran into a similar issue while testing this, but it turned out that my problem was Windows icon cache rather than the icon itself.  If you [refresh the cache](http://superuser.com/questions/499078/refresh-icon-cache-without-rebooting), does it get corrected?

**Comment by sbauer322** [comment]
Heh, you are correct. It was a caching issue. Just updating the documentation should be fine.

**Comment by TimothyDJewell** [comment]
@sbauer322 I've added it to the docs, but I'm not sure I'm happy with the way it reads.  I'm certainly open to feedback if there's a preferred way to do this.

**Comment by sbauer322** [comment]
How about something like the following:

In order to rebrand a build's resulting executable, you will need rcedit on your path to allow the build to brand the executable with the Light Table icon.... Otherwise, it will be branded with the default electron icon. There is a [pre-built release](https://github.com/electron/rcedit/releases) of rcedit available on GitHub.

**Comment by sbauer322** [comment]
Looks great @TimothyDJewell, thank you!

**Pull request merged**
