### PR TITLE
Bump default plugin versions

### PR DESCRIPTION
**Pull request by kenny-evitt**
@cldwalker @rundis FYI

Plugins with changes not included in the latest version:

 - [Paredit](https://github.com/LightTable/Paredit/commits/master)
 - [CSS](https://github.com/LightTable/CSS/commits/master)
 - [HTML](https://github.com/LightTable/HTML/commits/master)

### CODE REVIEW

**Comment by cldwalker** [comment]
@kenny-evitt Thanks for looking into this. If you don't mind, I'd like to keep this open and bump to Clojure 0.2.0. I should have that out by Friday

**Comment by kenny-evitt** [comment]
@cldwalker I'll followup this weekend then.

**Comment by cldwalker** [comment]
Clojure 0.2.0 has been released. Feel free to bump "version" in version.json to 0.8.0-alpha while you're at it since we're about to freeze master

**Comment by kenny-evitt** [comment]
@cldwalker What about [*deploy/core/package.json*](https://github.com/LightTable/LightTable/blob/master/deploy/core/package.json)? Should we update that `version` to `0.8.0-alpha` too?

**Comment by cldwalker** [comment]
@kenny-evitt Yep. It's not functionally important but makes sense for consistency

**Comment by kenny-evitt** [comment]
@cldwalker I also updated the core Leiningen project, for extra consistency.

**Comment by cldwalker** [comment]
Looks good! Feel free to merge :+1: :dancers:

**Pull request merged**
