### PR TITLE
#1903 Fixed default.behaviors file.ignore-pattern

### PR DESCRIPTION
**Pull request by Dadie**
For more information see #1903

### CODE REVIEW

**Comment by kenny-evitt** [comment]
Thanks for the PR!

But yikes – this seems a lot more ambitious than what your issue covers.

You need to escape `\b` as `\\b` – the former will be interpreted as a backspace character.

I don't understand some of the changes:

 - `(^\\..*)` to `^\\.(.*)` – honestly the original version seems to cover anything beginning with a period so the subsequent more-specific patterns seem superfluous.

Maybe you could split these changes into separate commits?

It'd be really nice to have some tests for this, i.e. a readable list of example file names that will be ignored.

As-is, let me review this for a bit and test that this is a sensible change.

@rundis – would you take a look at this too?

**Comment by Dadie** [comment]
First of all thanks for the quick reply. 
And thanks for having patient with me.

About the \b as \\b : 

* Missed that, sorry.

About ```(^\\..*)``` to ```^\\.(.*)``` : 

* I though the brackets where kind of "useless" as they didn't add anything to help to 
visualize what the RegEx is doing. The later one separates the first period from the second which makes th regEx (IMO) quite easier to read and to understand.

About tests:

* And how should this test look like? I could create a list, but how exactly should I test that list? (As I don't see any kind of test code in the project)

About more commits:

* I'll make for each term a single commit.

**Comment by Dadie** [comment]
I rewrote most of the code, split the commit in many small commit (each addressing a 'bug')

**Comment by kenny-evitt** [comment]
@Dadie thanks for the contribution!

The capturing group (i.e. the parentheses) in the first sub-pattern – `(^\\..*)` is extraneous and can be removed.

The patterns `\\.git`, `.DS_Store`, and `\\.nrepl-port` patterns can be removed.

The remaining 'dot' patterns – `\\.class$`, `\\.pyc$`, `\\.swp$`, and `\\.jar$` – should be retained.

`~` should be probably be `~$` too.

You're right that there are no tests. But for now it'd be nice if we just test manually, i.e. create a defined set of files and directories and confirm that they're visible or not in Light Table in the workspace.

**Comment by Dadie** [comment]
* Removed \\.git, \\.DS_Store, and \\.nrepl-port 370e869
* ~ to ~$ 4baf569
* Removed extraneous parentheses in file.ignore-pattern (^\\..*) 501d0d4

Tests for pattern ```^\\..*```
* http://regexr.com/3b7tl

Test for pattern ```\\.class$```
 * http://regexr.com/3b7to

Test for pattern ```\\.pyc$```
* http://regexr.com/3b7tr

Test for pattern ```~$```
* http://regexr.com/3b7tu

Test for pattern ```\\.swp$```
* http://regexr.com/3b7u1

Test for pattern ```\\.jar$```
* http://regexr.com/3b7u4

Test for pattern ```^target/```
* http://regexr.com/3b7ud

**Comment by kenny-evitt** [comment]
The first pattern can be simplified to `^\\.`.

Besides that, I think the changes are good. I want another committer to sign-off before merging. And contrary to what I told you earlier, I'd now rather this be squashed into a single commit.

@rundis What do you think about these changes?

**Comment by kenny-evitt** [comment]
@Dadie note that you're going to need to change one of your local behaviors files for now as we don't know when we're going to be able to make the next release.

**Comment by Dadie** [comment]
@kenny-evitt 

The first pattern can be simplified to ^\\. f07c586

Should I squash it now into a single commit or should I better wait for the other committer?

Also: my local behaviors is already loaded with the updated version :) But thanks for reminding me.

**Comment by kenny-evitt** [comment]
@Dadie You can go ahead and squash now; thanks.

**Comment by Dadie** [comment]
@kenny-evitt I squashed the commit

**Comment by rundis** [comment]
Looks good to me (but then again my regex foo is not up to scratch either).

**Comment by kenny-evitt** [comment]
@Dadie There's no real hurry to merge this as the core focus is to get the Atom/Electron version tested and released.

But I think this is a good opportunity to explore how to best add testing. I created [a branch in my LT fork](https://github.com/kenny-evitt/LightTable/tree/atom-shell-with-a-few-tests) for playing around with this. I started trying to get [*clojurescript.test*](https://github.com/cemerick/clojurescript.test) working.

In the source file *src/lt/objs/files.cljs*, I added a function `ignore?` that extracts a simple expression used in several places for excluding files based on the file-ignore pattern. I was thinking of adding a few tests with a very simple file-ignore – e.g. `#"a"` – to demonstrate that any file for which *any* portion matches the pattern will be ignored. The remaining tests will cover the default pattern.

Sorry in advance for the stupid mistakes in the test code I committed on that branch.

**Comment by kenny-evitt** [comment]
Bad news on adding tests – see #1647 for the first documented attempt:

 - [Adding a test suite to Light Table · Issue #1647 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1647)

I haven't gotten clojurescript.test to work for me, and I'm pinned to version *0.3.1* as newer versions require newer versions of ClojureScript than Light Table can use and updating ClojureScript is currently blocked by other changes that should be made first – see #1739:

 - [Update ClojureScript dependency · Issue #1739 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1739)

[Or, maybe we will need "to run the tests in LT itself".](https://github.com/LightTable/LightTable/issues/1647#issuecomment-58197749)

Any help is very much welcome.

**Comment by sbauer322** [comment]
This looks solid to me @kenny-evitt! I went through the regexr links and added each file/folder to a workspace in LT and compared the results - they were as desired.

I think we should merge this given that automated testing has stalled out for the time being... unless this PR was being held up from something else.

**Pull request merged**
