### PR TITLE
Adds cljs test support

### PR DESCRIPTION
**Pull request by kenny-evitt**

### CODE REVIEW

**Comment by kenny-evitt** [comment]
I installed PhantomJS on my Ubuntu box just now and ran `lein cljsbuild test`:

```
Compiling ClojureScript.
Compiling "deploy/core/node_modules/lighttable/bootstrap.js" from ["src" "tests"]...
Successfully compiled "deploy/core/node_modules/lighttable/bootstrap.js" in 98.014419699 seconds.
Running ClojureScript test: unit-tests
TypeError: 'undefined' is not a function (evaluating 'b.call(null, cljs.core.deref.call(null, cemerick.cljs.test.registered_fixtures))')

  file:///tmp/runner5809296835635268338.js.html:14404
  file:///tmp/runner5809296835635268338.js.html:14444
  file:///tmp/runner5809296835635268338.js.html:14461
  file:///tmp/runner5809296835635268338.js.html:14472
  file:///tmp/runner5809296835635268338.js.html:14454
  file:///tmp/runner5809296835635268338.js.html:14470
  file:///tmp/runner5809296835635268338.js.html:14643

Testing tests.dummy 

Ran 1  tests containing 1 assertions.
Testing complete: 0 failures, 0 errors.
```

**Comment by kenny-evitt** [comment]
@BenjaminVanRyseghem Previous attempts:

 - [Adding a test suite to Light Table · Issue #1647 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1647)
 - [A comment by myself from my previous attempt](https://github.com/LightTable/LightTable/issues/1038#issuecomment-113698697)
 - [Another comment by myself from my previous attempt](https://github.com/LightTable/LightTable/pull/1921#issuecomment-113699787)

**Comment by BenjaminVanRyseghem** [comment]
I would like to get rid off this TypeError, but in the meantime, it seems to work :smile:

**Comment by BenjaminVanRyseghem** [comment]
After some investigation, it sounds like an issue in `cemerick/clojurescript.test`.

Maybe an incompatibility with the cljs version we currently use

**Comment by BenjaminVanRyseghem** [comment]
But the output is still good

by example, running `lein cljsbuild test && echo 'it works'` output `it works` as expected

**Comment by kenny-evitt** [comment]
@BenjaminVanRyseghem Can you run a test that exercises some of the LT code itself? All of the earlier issues seemed to boil down to us being stuck on an old (and getting older) version of ClojureScript. No one has been able to figure out what needs to be fixed when bumping the ClojureScript version.

**Comment by kenny-evitt** [comment]
@BenjaminVanRyseghem Ideally, could you run some tests that fail and some that succeed? I'm curious whether we really could use the test output as-is even without bumping ClojureScript.

**Comment by cldwalker** [comment]
@BenjaminVanRyseghem Thanks for taking a look at this. As noted in #1647, adding a clojurescript test runner wasn't an issue. The issue encountered was writing any acceptance tests which require pulling in namespaces that depends on node-webkit/electron (which is most namespaces). This was last attempted with node-webkit. Perhaps this isn't an issue with electron. May also be worth investigating how other cljs projects are testing electron apps.

**Comment by BenjaminVanRyseghem** [comment]
@kenny-evitt Adding a failing test outputs:

~~~
Running ClojureScript test: unit-tests
TypeError: 'undefined' is not a function (evaluating 'b.call(null, cljs.core.deref.call(null, cemerick.cljs.test.registered_fixtures))')

  file:///var/folders/xl/b9mlm6gj2s5g21vd5qxzbq2r0000gn/T/runner985677419549062718.js.html:14404
  file:///var/folders/xl/b9mlm6gj2s5g21vd5qxzbq2r0000gn/T/runner985677419549062718.js.html:14444
  file:///var/folders/xl/b9mlm6gj2s5g21vd5qxzbq2r0000gn/T/runner985677419549062718.js.html:14461
  file:///var/folders/xl/b9mlm6gj2s5g21vd5qxzbq2r0000gn/T/runner985677419549062718.js.html:14472
  file:///var/folders/xl/b9mlm6gj2s5g21vd5qxzbq2r0000gn/T/runner985677419549062718.js.html:14454
  file:///var/folders/xl/b9mlm6gj2s5g21vd5qxzbq2r0000gn/T/runner985677419549062718.js.html:14470
  file:///var/folders/xl/b9mlm6gj2s5g21vd5qxzbq2r0000gn/T/runner985677419549062718.js.html:14710

Testing tests.dummy 

FAIL in (tests.dummy/test-numbers-fails) (:)
expected: (= 1 2)
  actual: (not (= 1 2))

Ran 2  tests containing 2 assertions.
Testing complete: 1 failures, 0 errors.
Subprocess failed
~~~

The output looks good enough to me :smile:

**Comment by kenny-evitt** [comment]
@BenjaminVanRyseghem As @cldwalker commented, this is only useful if we can test the actual LT code. Would you try testing a simple function in one of the LT namespaces?

A quick perusal of results for a Google search of "clojurescript electron" didn't turn up any real info on testing ClojureScript code targeting Electron. But I did find [some info that others are trying to solve the same problem](https://groups.google.com/forum/#!msg/clojurescript/WpRCu48gEDI/dgR5ZxDU_0cJ).

**Comment by BenjaminVanRyseghem** [comment]
@kenny-evitt yep, the main issue is that it's a weird mix of node and browser.

So my idea was instead of using a lein plugin, starting LT with a flag to run tests and exit LT afterward.

But for that I open the #1952 to try this approach. I will see if I can come up with something there :smile:

**Comment by BenjaminVanRyseghem** [comment]
Now it seems to work :smile:

Please feel free to prove me wrong so we can try to finally catch up with the cljs release :smile:

**Comment by cldwalker** [comment]
Closing as #1996 is more of the testing direction we want as mentioned in #1647. Thanks for the effort. Hopefully we'll be able to rely on cljs.test directly once we have time to focus on a cljs upgrade

**Pull request closed without merging**
