### PR TITLE
Prelude to clojurescript upgrade

### PR DESCRIPTION
**Pull request by cldwalker**
Unlike previous attempts, this PR only address upgrade todos for #1973 that are compatible with the current version of ClojureScript. By doing this upfront work, we make the upgrade branch more manageable and closer within reach :smile: . This PR does the following:

* Fixes all clojurescript warnings that future versions of lein-cljsbuild will pick up. These are warnings that we shouldn't be causing anyway so these are uncontroversial.
* This introduces a second build target for generating cljsDeps.js as done by @BenjaminVanRyseghem in #1952. Having a second build target can introduce unreliability in `lein cljsbuild once`. I'll double check to see if I need to update script/build.sh in some way. This build target only needs to be run when we upgrade cljs.
* Remove our dependence on `js->clj` and `clj->js`. This is necessary for an upgrade as we can't continue to depend on home-rolled versions of such a core fn. This change has some small risk. I"ll run through the QA checklist but I don't expect to find any issues. If you're curious how I determined what plugins use our `js->clj`, it was with [this search](https://github.com/search?l=&q=user%3ALightTable+js-%3Eclj&ref=advsearch&type=Code&utf8=%E2%9C%93).

@kenny-evitt @rundis I'll be using this branch exclusively until we merge. I plan to merge Monday or Tuesday unless you have any concerns

### CODE REVIEW

**Comment by kenny-evitt** [comment]
I'm running this branch now. I'm not doing any work with Clojure or ClojureScript tho.

**Comment by cldwalker** [comment]
I ran through most of the QA checklist and haven't seen any issues. I'll double check cljsbuild reliability and if that's good merge tomorrow

**Comment by kenny-evitt** [comment]
I've been running a build of this branch on a Mac and a Windows computer without issue.

**Comment by cldwalker** [comment]
@kenny-evitt @rundis Fyi. Now that this branch is merged you should run `lein cljsbuild [once|auto] app` when recompiling LT cljs

**Pull request merged**
