### PR TITLE
folder renaming updated in the document manager - fixes #2232

### LINKED ISSUE #2232: Renaming a folder prevents saving already opened files
One small issue: after renaming a folder, its contained files opened before the renaming cannot be saved. One way around it is to copy the file content somewhere, close the file and "discard changes", and re-open that file and paste the changed content back.

### Steps to Reproduce

 1. Have some files opened in the editor.
 2. In the workspace browser, right-click on the folder these files are contained it, and choose to rename it.
 3. After renaming the folder, make changes in the opened files and try to save them.

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |    0.8.1 (binary version: (0.34.5)     |
| Operating system                 |   Ubuntu 16.04      |

### Error Messages

```
Invalid behavior: :lt.objs.editor.file/file-save
```

### PR DESCRIPTION
**Pull request by tomtau**

### CODE REVIEW

**Comment by sbauer322** [comment]
This works great for me. Thanks for the fix!

**Comment by kenny-evitt** [comment]
@tomtau This looks good to me. Let me get some eyeballs from the other two people on the core team and see if we can get this merged.

@cldwalker @rundis Thoughts? Feelings?

**Comment by sbauer322** [comment]
I did notice one thing - after the folder is renamed the tab still contains the previous file path until the file is updated in some way. Seems like the tab is not being refreshed?

Below are a couple of screenshots of this:

tab-file-path-not-updating-1

tab-file-path-not-updating-2

**Comment by sbauer322** [comment]
Looks like you can fix the issue above with a nicely placed `(object/raise this :refresh!)`. I believe this is a separate issue and was simply revealed from your pull request.

Not to further muddle things, but I have a separate pull request that will fix what was pointed out... coincidently I end up touching the same code.

**Comment by tomtau** [comment]
@sbauer322 A good spot! It seems the file doesn't need to be updated -- if you click on the tab name or the corresponding file in the workspace sidebar, the path shown in the mouse hover is updated.
Anyway, should we add the explicit refresh to this fix, or open a separate issue, or leave it for this PR: https://github.com/LightTable/LightTable/pull/2234 ?

**Comment by sbauer322** [comment]
Ah, sorry, that is more along the lines of what I meant - update was a poor choice of words to use.

I'm comfortable with leaving it for #2234 (I already integrated your work and this fix), but I suppose it is up to those on the core team ;-)

**Comment by sbauer322** [comment]
Heh - looks like I spoke too soon. `(object/raise this :refresh!)` didn't fix the issue... I must have clicked the tab and it updated <_>

I can take another quick look and open a separate issue if it comes to it.

**Comment by sbauer322** [comment]
Excellent news! This appears to be working properly in the latest iteration of PR #2234, including that tab name not being refreshed right away thing.

**Comment by sbauer322** [comment]
@kenny-evitt, it might be worthwhile to continue this pull request irrelevant of #2234 as that pull request is likely going to take time to get approval. #2234 integrated this fix so nothing will be lost when it is merged.

**Comment by kenny-evitt** [comment]
@sbauer322 I was thinking the same thing. I'll test this soonish and try to get another core team member to signoff too.

**Comment by rundis** [comment]
Looks good to me. feel free to merge @kenny-evitt

**Comment by kenny-evitt** [comment]
@rundis Why hello friend! Thanks for the feedback.

**Comment by kenny-evitt** [comment]
@sbauer322 Would you please share the relevant code with the necessary change(s) to fix [the path displayed in the tap mouseover not updatin](https://github.com/LightTable/LightTable/pull/2233#issuecomment-236776564) issue you mentioned so @tomtau can incorporate it into this PR?

**Comment by sbauer322** [comment]
@kenny-evitt @tomtau I'll be honest... I'm not confident the changes that fix this from my PR can easily be integrated here. 

In general, I suspect that the folder being renamed is not updating/notifying its children about the change. Furthermore, it does not seem like the line `(object/raise this :refresh!)` within the `::rename-folder` behavior actually does anything to folder objects... When I look in the folder atom I do not see any refresh behaviors associated with it.

Of course, this assumes I am correctly diagnosing the problem and not just misleading us.

**Comment by tomtau** [comment]
@sbauer322 @kenny-evitt one quick fix for refreshing the displayed onhover tab path is by adding
```
(cmd/exec! :tabs.next)
(cmd/exec! :tabs.prev)
```
at the end of the rename-folder's reaction.

**Comment by sbauer322** [comment]
That sounds good to me as a temporary solution, but you should await confirmation from @kenny-evitt or another maintainer... I'm not aware of the possible implications (or if there even are any).

**Comment by sbauer322** [comment]
Regrettably, I've apparently managed to not include the fix for 'the path displayed in the tap mouseover not updating' issue, described within this PR, in the rename PR. Currently working to restore...

@kenny-evitt, for clarify and cleanliness, could we move this discussion into its own issue? I hate that we are cluttering up @tomtau 's otherwise fine PR for something issue not within scope.

**Comment by rundis** [comment]
Sorry for being lazy and not parsing the above discussion fully. @tomtau @sbauer322 this fixes the issue stated in the title. If so I'm happy to merge in and take further fixes/improvements in separate issues/prs.

**Comment by sbauer322** [comment]
Yes, sorry @rundis , the discussion about that discovered issue was fairly confusing.

From what I recall, this PR does indeed fix the original issue.

**Comment by rundis** [comment]
tx so much for the patience !

**Pull request merged**
