### PR TITLE
Bump LT version to *0.8.0*

### PR DESCRIPTION
**Pull request by kenny-evitt**
Bump version for the next release.

### CODE REVIEW

**Comment by cldwalker** [comment]
@kenny-evitt Looks good! I think there's a minor conflict to resolve in project.clj and then feel free to merge

**Comment by kenny-evitt** [comment]
@cldwalker What's the minor conflict in *project.clj*?

**Comment by cldwalker** [comment]
@kenny-evitt Try merging locally and you'll see. git is being dumb about merging two adjacent lines

**Comment by kenny-evitt** [comment]
@cldwalker Just realized the same thing.

**Pull request merged**
