### PR TITLE
make npm check faster/simpler

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
This will need to be verified as working on Windows (as I don't have access to it).

Signed-off-by: Ryan P.C. McQuen <ryan.q@linux.com>

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
You could also use a similar check for `lein`.

https://github.com/LightTable/LightTable/blob/master/script/build.sh#L11

**Comment by ryanpcmcquen** [comment]
Let me know if that sounds reasonable, and I can rebase this to also change the `lein` check (or just open another *PR*).

**Comment by cldwalker** [comment]
Thanks for the pull but this refactor isn't a high priority as the speed of this check is one to two magnitudes smaller than other processes e.g. downloading electron and building clojurescript. Closing but willing to reconsider if you or @kenny-evitt  can verify this works on Cygwin Windows

**Comment by ryanpcmcquen** [comment]
@kenny-evitt do you have a Windows machine to test this on?

**Comment by Tarabyte** [comment]
```
$ bash build.sh
which: no lein in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Haskell/bin:...)
Please install leiningen before running this script.
```

**Comment by ryanpcmcquen** [comment]
@Tarabyte, thanks for checking that!

**Comment by ryanpcmcquen** [comment]
@cldwalker @kenny-evitt reopened with lein check as well, here: https://github.com/LightTable/LightTable/pull/2076

Thanks to @Tarabyte for verifying that it works on *cygwin*.

**Comment by Tarabyte** [comment]
@ryanpcmcquen  I've installed leiningen on my machine. It looks like `which lein` fails on windows using cygwin.
```
$ which lein
which: no lein in (../cygdrive/c/Users/Юрий/.lein/bin:/usr/lib/lapack)
```

Though `which lein.bat` works
```
$ which lein.bat
/cygdrive/c/Users/Юрий/.lein/bin/lein.bat
```

**Comment by ryanpcmcquen** [comment]
@Tarabyte what does this say:

    lein version

**Comment by Tarabyte** [comment]
```
(cmd)
C:\cygwin64\bin>lein version
Leiningen 2.5.3 on Java 1.8.0_51 Java HotSpot(TM) 64-Bit Server VM

(cygwin)
C:\cygwin64\bin>cygwin
Юрий@Lenovo-PC ~
$ lein version
bash: lein: command not found
```

**Comment by ryanpcmcquen** [comment]
@Tarabyte does the current build script work?

https://github.com/LightTable/LightTable/blob/master/script/build.sh

**Comment by ryanpcmcquen** [comment]
We could put a double check in there:

    [ `which lein` ] || [ `which lein.bat` ] || { echo >&2 "Please install leiningen before running this script."; exit 1; }

I'd also like to know the current outcome for `npm`, is that under some executable form as well?

**Comment by Tarabyte** [comment]
@ryanpcmcquen Wait, I believe the problem is with my current lein installation. It has no `bin\lein` file to begin with. :smile:

**Comment by kenny-evitt** [comment]
@cldwalker This works for me on one of my Windows computers and I'm pretty sure I didn't explicitly install `which`, so I think this is okay to merge (or rather #2076).

**Comment by ryanpcmcquen** [comment]
@Tarabyte & @kenny-evitt thanks for testing this!

**Pull request closed without merging**
