### PR TITLE
Update cljs

### PR DESCRIPTION
**Pull request by BenjaminVanRyseghem**
In order to try another approach for #1949 , I bumped all the dependencies to the latest.

I fixed all the warnings and errors, but the editor is still quite not loading.
If someone wants to have a look at it, it open this PR while I continue working on it :smile:

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Now it seems to work :smile:

Please feel free to prove me wrong so we can try to finally catch up with the cljs release :smile:

**Comment by rundis** [comment]
well...

I don't think it ever actually compiled the clojurescript code due an error in build.sh
`lein cljsbuild clean && lein cljsbuild once` fails since cljsbuild doesn't have the clean task anymore (it's hooked into lein clean in more recent version).

So I commented out the clean bit and just left `lein cljsbuild once`

I manage to start the editor, but it's not exactly particularily usable
Lots of:
```
ReferenceError: arguments$ is not defined
    at funcs.theadfunc57 (eval at <anonymous> (/Users/mrundberget/projects/LightTable-Projects/LightTable/builds/lighttable-0.8.0-mac/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/background/threadworker.js:39:43), <anonymous>:2:21)
    at process.<anonymous> (/Users/mrundberget/projects/LightTable-Projects/LightTable/builds/lighttable-0.8.0-mac/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/background/threadworker.js:43:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:169:7)
    at handleMessage (child_process.js:306:10)
    at Pipe.channel.onread (child_process.js:334:11)
```

Might be something to do with cljsdeps.js. Ref conversation here: https://github.com/LightTable/LightTable/commit/8e73f59891c45f73a1b985fed69795d1061a8ecf

**Comment by rundis** [comment]
Tried compiling a cljsDeps.js manually (using clojurecript 1.7) and using that, but still no luck (:

**Comment by BenjaminVanRyseghem** [comment]
Ok, now I can reproduce this, I am having a look at it :smile:

**Comment by BenjaminVanRyseghem** [comment]
I tried to fix the thread issue, but without much success.

At least it seems the issue comes from `auto_complete.cljs`.
If I remove it, I do not have the error anymore, but LT doesn't look fully functional though

**Comment by cldwalker** [comment]
Thanks for taking a look at this gnarly issue. It may be worth chatting with @brabadu as he has done some work on [updating fetch](https://github.com/LightTable/fetch/pull/17) with this issue in mind. Also, be aware of [cljs.cljs](https://github.com/LightTable/LightTable/blob/master/src/lt/util/cljs.cljs) which may need to be updated and that LT still depends on old versions of `js->clj` and `clj->js`

**Comment by BenjaminVanRyseghem** [comment]
@cldwalker I really think that all this little things should be documented somewhere...

Or maybe I did not find the doc, but how someone can possibly imagine that there is a `cljsDeps` to compile by hand? And that there is a custom `clj->js`?

BTW why reimplementing them?

**Comment by cldwalker** [comment]
@BenjaminVanRyseghem Agree we should document cljsDeps in doc/for-committers.md. Keep in mind information around upgrading clojurescript won't be documented anywhere because the current team hasn't upgraded clojurescript on LT before. Those helper fns were added I think before clojurescript got them

**Comment by kenny-evitt** [comment]
@BenjaminVanRyseghem @cldwalker I'll gladly document 'cljsDeps' in [*for-committers.md*](https://github.com/LightTable/LightTable/blob/master/doc/for-committers.md) – what should it say?

Generally tho, I'm pretty happy with stuff just being documented in GitHub issues. This seems like the kind of thing that would be best 'documented' with a clearly named script, but maybe I'm not understanding what's being discussed.

@rundis What exactly did "compiling a cljsDeps.js manually (using clojurecript 1.7)" involve?

I'm a little unclear about what [*cljsDeps.js*](https://github.com/LightTable/LightTable/blob/master/deploy/core/node_modules/clojurescript/cljsDeps.js) is exactly. Is it just the *cljs_deps.js* file that the ClojureScript compiler outputs?

**Comment by BenjaminVanRyseghem** [comment]
@kenny-evitt First I would love to know what it's used for

I updated `project.clj` to compile automatically `cljsDeps.js`, as I do not believe in "compile this by hand" steps :smile:

**Comment by rundis** [comment]
@BenjaminVanRyseghem see the last comment from @cldwalker in this commit : https://github.com/LightTable/LightTable/commit/8e73f59891c45f73a1b985fed69795d1061a8ecf

**Comment by BenjaminVanRyseghem** [comment]
@rundis Thanks :smile:

**Comment by rundis** [comment]
@BenjaminVanRyseghem A small note when trying to do this myself a little while ago.
lein-cljsbuild removed the clean task in version 1.0.6. So I added a hook as per the readme:
`:hooks [leiningen.cljsbuild]`

That cleans up anything in `deploy/core/node_modules/lighttable/cljs/`

**Comment by cldwalker** [comment]
@BenjaminVanRyseghem Thanks for this PR. It was helpful in doing #2072. Closing this as #2072 does most of what's covered in this PR. I've also added the explanation of cljsDeps to the committers doc as suggested. While we haven't finished upgrading cljs, it is easier to attempt it with #2072 in. We'll be tracking progress towards the upgrade in #1973

**Pull request closed without merging**
